CXX             := g++
CXXFLAGS        := -O3 -Wall -shared -std=c++11 -fPIC -Iinclude
LDFLAGS         :=

LIB             := 
OBJS            :=

all:

%.o: %.cpp
	$(CXX) -o $@ -c $^ $(CXXFLAGS)

test:
.PHONY: test

clean:
.PHONY: clean
